# 1(a)

In [1]:
foo=c(6,9,7,3,6,7,9,6,3,6,6,7,1,9,1)
foo>=6

[1]  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE
[13] FALSE  TRUE FALSE

In [2]:
print(foo==6)
print(which(foo==6))
print(foo[foo==6])

 [1]  TRUE FALSE FALSE FALSE  TRUE FALSE FALSE  TRUE FALSE  TRUE  TRUE FALSE
[13] FALSE FALSE FALSE
[1]  1  5  8 10 11
[1] 6 6 6 6 6


In [3]:
print(foo>=6)
print(which(foo>=6))
print(foo[foo>=6])

 [1]  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE
[13] FALSE  TRUE FALSE
 [1]  1  2  3  5  6  7  8 10 11 12 14
 [1] 6 9 7 6 7 9 6 6 6 7 9


In [4]:
print(foo<8)
print(which(foo<8))
print(foo[foo<8])

 [1]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE
[13]  TRUE FALSE  TRUE
 [1]  1  3  4  5  6  8  9 10 11 12 13 15
 [1] 6 7 3 6 7 6 3 6 6 7 1 1


In [5]:
print(foo!=6)
print(which(foo!=6))
print(foo[foo!=6])

 [1] FALSE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE FALSE  TRUE FALSE FALSE  TRUE
[13]  TRUE  TRUE  TRUE
 [1]  2  3  4  6  7  9 12 13 14 15
 [1] 9 7 3 7 9 3 7 1 9 1


# 1(b)

In [6]:
bar=foo[-(1:3)]
arr<-array(data=bar,dim=c(2,2,3))
print(arr)

, , 1

     [,1] [,2]
[1,]    3    7
[2,]    6    9

, , 2

     [,1] [,2]
[1,]    6    6
[2,]    3    6

, , 3

     [,1] [,2]
[1,]    7    9
[2,]    1    1



In [7]:
print(arr<=7)
print(which(arr<=7))
print(arr[arr<=7])

, , 1

     [,1]  [,2]
[1,] TRUE  TRUE
[2,] TRUE FALSE

, , 2

     [,1] [,2]
[1,] TRUE TRUE
[2,] TRUE TRUE

, , 3

     [,1]  [,2]
[1,] TRUE FALSE
[2,] TRUE  TRUE

 [1]  1  2  3  5  6  7  8  9 10 12
 [1] 3 6 7 6 3 6 6 7 1 1


In [8]:
print(arr+2<=7)
print(which(arr+2<=7))
print(arr[arr+2<=7])

, , 1

      [,1]  [,2]
[1,]  TRUE FALSE
[2,] FALSE FALSE

, , 2

      [,1]  [,2]
[1,] FALSE FALSE
[2,]  TRUE FALSE

, , 3

      [,1]  [,2]
[1,] FALSE FALSE
[2,]  TRUE  TRUE

[1]  1  6 10 12
[1] 3 3 1 1


# 1(c)

In [9]:
print(any(arr<=7))
print(any(arr+2<=7))

[1] TRUE
[1] TRUE


In [10]:
print(all(arr<=7))
print(all(arr+2<=7))

[1] FALSE
[1] FALSE


# 2

In [11]:
foo=c(6,9,7,3,6,7,9,9,1,6,3,6,6,7,1)
bar=c(6,7,9,9,1,6,3,6,6,6,9,7,3,6,7)
baz=foo+bar

In [12]:
print((baz>=14)&(baz!=15))
print(which((baz>=14)&(baz!=15)))
print(baz[(baz>=14)&(baz!=15)])

 [1] FALSE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[13] FALSE FALSE FALSE
[1] 2 3
[1] 16 16


In [13]:
myvec=baz/foo
print((myvec>4)|(myvec<=2))
print(which((myvec>4)|(myvec<=2)))
print(myvec[(myvec>4)|(myvec<=2)])

 [1]  TRUE  TRUE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE FALSE
[13]  TRUE  TRUE  TRUE
 [1]  1  2  5  6  7  8  9 10 13 14 15
 [1] 2.000000 1.777778 1.166667 1.857143 1.333333 1.666667 7.000000 2.000000
 [9] 1.500000 1.857143 8.000000


# 3(a)

In [14]:
foo <- c(7,5,6,1,2,10,8,3,8,2)
bar=foo[foo>=5]
bar

[1]  7  5  6 10  8  8

In [15]:
myvec=foo[-which(foo>=5)]
print(myvec)

[1] 1 2 3 2


# 3(b)

In [16]:
baz=matrix(bar,nrow=2,ncol=3,byrow=T)

In [17]:
baz[baz==8]=baz[1,2]^2
baz

[,1] [,2] [,3]
[1,]  7    5    6  
[2,] 10   25   25

In [18]:
all((baz<=25)&(baz>4))

[1] TRUE

# 4(a)

In [19]:
cat("\"The quick brown fox\n\tjumped over\n\t\tthe lazy dogs\"")

"The quick brown fox
	jumped over
		the lazy dogs"

# 4(b)

In [20]:
mystr="Two 6-packs for $16.99"
substr(mystr,5,10)=="6-pack"

[1] TRUE

In [21]:
sub(pattern = "16.99",replacement = "14.99",x=mystr)

[1] "Two 6-packs for $14.99"

# 5(a)

In [22]:
myseq=seq(-4,4,length.out=20)
mymat=matrix(c(F,T,T,T,F,T,T,F,F),nrow=3,ncol=3,byrow=F)
myvec=c("don","quixote")
myfac=factor(c("LOW","MED","LOW","MED","MED","HIGH"))

In [23]:
mymat[c(2,1),c(2,3)]

[,1]  [,2] 
[1,] FALSE FALSE
[2,]  TRUE  TRUE

In [24]:
myvec=sub(pattern = c("quixote"),replacement = c("Quixote"),x=myvec)
newvec=sub(pattern = c("don"),replacement = c("Don"),x=myvec)

In [25]:
cat("\"Windmills! ATTACK!\"\n\t-\\",newvec[1]," ",newvec[2],"/-",sep='')

"Windmills! ATTACK!"
	-\Don Quixote/-

In [26]:
myseq[myseq>1]

[1] 1.052632 1.473684 1.894737 2.315789 2.736842 3.157895 3.578947 4.000000

In [27]:
print(myfac=="MED")
print(which(myfac=="MED"))
print(myfac[myfac=="MED"])

[1] FALSE  TRUE FALSE  TRUE  TRUE FALSE
[1] 2 4 5
[1] MED MED MED
Levels: HIGH LOW MED
