In [1]:
import numpy as np
import fractions
np.set_printoptions(formatter={'all':lambda x:str(fractions.Fraction(x).limit_denominator())})
x=np.array([[1,0],[2,-1],[1,2]])
a=np.array([1,-2])
n=3
m=1
p=2
print(a @ np.linalg.inv(x.T @ x) @ a.T)

0.9666666666666667


In [2]:
print(a @ x.T @x @a.T)

26


In [3]:
print(1/6+4/5)

0.9666666666666667


In [4]:
print(a@np.linalg.inv(x.T@x)@x.T)
beta=np.linalg.inv(x.T@x)@x.T
out=a@np.linalg.inv(x.T@x)@x.T

[1/6 11/15 -19/30]


In [5]:
print(out)

[1/6 11/15 -19/30]


In [7]:
x=np.array([[1,0,0],[0,1,0],[0,0,1],[-1,-1,-1]])
x.T@x

array([[2, 1, 1],
       [1, 2, 1],
       [1, 1, 2]])

In [9]:
x@np.linalg.inv(x.T@x)@x.T

array([[3/4, -1/4, -1/4, -1/4],
       [-1/4, 3/4, -1/4, -1/4],
       [-1/4, -1/4, 3/4, -1/4],
       [-1/4, -1/4, -1/4, 3/4]])

In [17]:
x=np.array([[1,-1,1,-1]])
x

array([[1, -1, 1, -1]])

In [19]:
x.T@x

array([[1, -1, 1, -1],
       [-1, 1, -1, 1],
       [1, -1, 1, -1],
       [-1, 1, -1, 1]])